### PR TITLE
added options for permanent 301 redirects

### PR DESCRIPTION
**Pull request by affan2**
set SOLID_I18N_USE_PERMANENT_DEFAULT_PREFIX_REDIRECT = True
if using SOLID_I18N_DEFAULT_PREFIX_REDIRECT

set SOLID_I18N_USE_PERMANENT_REDIRECTS = True
if using SOLID_I18N_USE_REDIRECTS

### CODE REVIEW

**Comment by samjacoby** [comment]
Haha. I just put in a PR for the same thing!

**Comment by st4lk** [comment]
Mohammed, thank you for pull request!
The idea to use 301 redirects in case of `SOLID_I18N_DEFAULT_PREFIX_REDIRECT = True` is really good, so i think it is better to do so be default.
It is already done in another pull request #24 thanks to @samjacoby  .
I'll publish new release soon.

**Comment by st4lk** [comment]
#24 now in pypi [v1.1.0](https://pypi.python.org/pypi/solid_i18n)

**Comment by st4lk** [comment]
Closing as duplicate of #24

**Pull request closed without merging**
